/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.Vclients;
import Logic.ConnectClient;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabio
 */
public class frm_clients extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_clients
     */
    public frm_clients() {
        initComponents();
        componentDisable();
        showSearch("null");     
    }

   private String action="save";
    
    //Disable table colum
    void  hide_column(){
         TB_Lista.getColumnModel().getColumn(0).setMaxWidth(0);
         TB_Lista.getColumnModel().getColumn(0).setMinWidth(0);
         TB_Lista.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    void componentDisable(){
        txt_id_peop.setVisible(false);
        txt_name_peop.setVisible(false);
        txt_father_peop.setVisible(false);
        txt_mother_peop.setVisible(false);
        txt_adress_peop.setVisible(false);
        txt_docum_peop.setVisible(false);
        cmb_typeDocum_peop.setVisible(false);
        txt_phone_peop.setVisible(false);
        txt_cod_cli.setVisible(false);
        txt_email_peop.setVisible(false);
        
        btn_salvar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        
        txt_id_peop.setText("");
        txt_name_peop.setText("");
        txt_father_peop.setText("");
        txt_mother_peop.setText("");
        txt_adress_peop.setText("");
        txt_docum_peop.setText("");
        txt_phone_peop.setText("");
        txt_cod_cli.setText("");
        txt_email_peop.setText("");
    }

      void componentEnable(){
        txt_id_peop.setVisible(false);
        txt_name_peop.setVisible(true);
        txt_father_peop.setVisible(true);
        txt_mother_peop.setVisible(true);
        txt_adress_peop.setVisible(true);
        txt_docum_peop.setVisible(true);
        cmb_typeDocum_peop.setVisible(true);
        txt_phone_peop.setVisible(true);
        txt_cod_cli.setVisible(true);
        txt_email_peop.setVisible(true);
        
        btn_novo.setEnabled(true);
        btn_salvar.setEnabled(true);
        btn_cancelar.setEnabled(true);
        
        txt_id_peop.setText("");
        txt_name_peop.setText("");
        txt_father_peop.setText("");
        txt_mother_peop.setText("");
        txt_adress_peop.setText("");
        txt_docum_peop.setText("");
        txt_phone_peop.setText("");
        txt_cod_cli.setText("");
        txt_email_peop.setText("");
    }  
      
      void showSearch(String searching){
          
          try {
              DefaultTableModel model;
              ConnectClient func=new ConnectClient();
              model = func.showSearch(searching);
              TB_Lista.setModel(model);
              
              hide_column();
              lbl_registros.setText("Total Registros "+Integer.toString(func.recordTotal));
          } catch (Exception e) {
                 JOptionPane.showConfirmDialog(null, e);
          }          
      }    


    void cleanField(){
        txt_id_peop.setText("");
        txt_name_peop.setText("");
        txt_father_peop.setText("");
        txt_mother_peop.setText("");
        txt_adress_peop.setText("");
        txt_docum_peop.setText("");
        txt_phone_peop.setText("");
        txt_cod_cli.setText("");
        txt_email_peop.setText("");
    }         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpa_cadQuartos = new javax.swing.JPanel();
        lbl_cadQuarto = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name_peop = new javax.swing.JTextField();
        lbl_docum = new javax.swing.JLabel();
        txt_docum_peop = new javax.swing.JTextField();
        lbl_tipoDoc = new javax.swing.JLabel();
        cmb_typeDocum_peop = new javax.swing.JComboBox<>();
        btn_novo = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        txt_id_peop = new javax.swing.JTextField();
        lbl_father = new javax.swing.JLabel();
        txt_father_peop = new javax.swing.JTextField();
        lbl_mother = new javax.swing.JLabel();
        txt_mother_peop = new javax.swing.JTextField();
        lbl_adress = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email_peop = new javax.swing.JTextField();
        lbl_phone = new javax.swing.JLabel();
        txt_phone_peop = new javax.swing.JTextField();
        lbl_name1 = new javax.swing.JLabel();
        txt_cod_cli = new javax.swing.JTextField();
        jsc_adress_peop = new javax.swing.JScrollPane();
        txt_adress_peop = new javax.swing.JTextArea();
        jpa_listaQuartos = new javax.swing.JPanel();
        lbl_cadQuarto1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TB_Lista = new javax.swing.JTable();
        txt_pesquisar = new javax.swing.JTextField();
        lbl_pesquisar = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        lbl_registros = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Clientes");

        jpa_cadQuartos.setForeground(new java.awt.Color(204, 204, 204));

        lbl_cadQuarto.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lbl_cadQuarto.setText("Cadastro de Clientes");

        lbl_name.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_name.setText("Nome");

        txt_name_peop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_name_peopActionPerformed(evt);
            }
        });

        lbl_docum.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_docum.setText("Documento");

        txt_docum_peop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_docum_peopActionPerformed(evt);
            }
        });

        lbl_tipoDoc.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_tipoDoc.setText("Tipo Doc");
        lbl_tipoDoc.setPreferredSize(new java.awt.Dimension(28, 13));

        cmb_typeDocum_peop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RG", "CPF", "CNH", "MILITAR", "MEDICA", "AOB", " " }));
        cmb_typeDocum_peop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_typeDocum_peopActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/novo.GIF"))); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/cancelar.png"))); // NOI18N
        btn_cancelar.setText("Limpar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/salvar.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        lbl_father.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_father.setText("Pai");

        txt_father_peop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_father_peopActionPerformed(evt);
            }
        });

        lbl_mother.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_mother.setText("Mãe");

        txt_mother_peop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mother_peopActionPerformed(evt);
            }
        });

        lbl_adress.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_adress.setText("Endereço");

        lbl_email.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_email.setText("Email");

        txt_email_peop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_email_peopActionPerformed(evt);
            }
        });

        lbl_phone.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_phone.setText("Telefone");

        txt_phone_peop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phone_peopActionPerformed(evt);
            }
        });

        lbl_name1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_name1.setText("Cod Cliente");

        txt_cod_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cod_cliActionPerformed(evt);
            }
        });

        txt_adress_peop.setColumns(20);
        txt_adress_peop.setRows(5);
        jsc_adress_peop.setViewportView(txt_adress_peop);

        javax.swing.GroupLayout jpa_cadQuartosLayout = new javax.swing.GroupLayout(jpa_cadQuartos);
        jpa_cadQuartos.setLayout(jpa_cadQuartosLayout);
        jpa_cadQuartosLayout.setHorizontalGroup(
            jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                        .addComponent(lbl_phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_phone_peop, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_email_peop))
                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                        .addComponent(lbl_cadQuarto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id_peop, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                        .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_adress)
                            .addComponent(lbl_father)
                            .addComponent(lbl_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_father_peop, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_name_peop, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_typeDocum_peop, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                                        .addComponent(lbl_mother)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_mother_peop))
                                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                                        .addComponent(lbl_name1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_cod_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                                        .addComponent(lbl_docum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_docum_peop))))
                            .addComponent(jsc_adress_peop)))
                    .addComponent(lbl_tipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpa_cadQuartosLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jpa_cadQuartosLayout.setVerticalGroup(
            jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadQuarto)
                    .addComponent(txt_id_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_name1)
                    .addComponent(txt_cod_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_father)
                    .addComponent(txt_father_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mother)
                    .addComponent(txt_mother_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_typeDocum_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_docum)
                    .addComponent(txt_docum_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_adress)
                    .addComponent(jsc_adress_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_email)
                        .addComponent(txt_email_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_phone)
                        .addComponent(txt_phone_peop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpa_listaQuartos.setForeground(new java.awt.Color(204, 204, 204));

        lbl_cadQuarto1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lbl_cadQuarto1.setText("Lista de Clientes");

        TB_Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TB_Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_ListaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TB_Lista);

        txt_pesquisar.setName(""); // NOI18N

        lbl_pesquisar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_pesquisar.setText("Pesquisar");

        btn_sair.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/cancelar.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/novo.GIF"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_apagar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/salvar.png"))); // NOI18N
        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        lbl_registros.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_registros.setText("Registros");

        javax.swing.GroupLayout jpa_listaQuartosLayout = new javax.swing.GroupLayout(jpa_listaQuartos);
        jpa_listaQuartos.setLayout(jpa_listaQuartosLayout);
        jpa_listaQuartosLayout.setHorizontalGroup(
            jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                        .addGroup(jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cadQuarto1)
                            .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                                .addComponent(lbl_pesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_apagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sair)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpa_listaQuartosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_registros)
                .addGap(31, 31, 31))
        );
        jpa_listaQuartosLayout.setVerticalGroup(
            jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                .addComponent(lbl_cadQuarto1)
                .addGap(18, 18, 18)
                .addGroup(jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_sair)
                    .addComponent(btn_apagar)
                    .addComponent(lbl_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpa_cadQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpa_listaQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpa_listaQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpa_cadQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_name_peopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_name_peopActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Insira o nome do cliente");
        txt_name_peop.transferFocus();
    }//GEN-LAST:event_txt_name_peopActionPerformed
 
    private void txt_docum_peopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_docum_peopActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Insira o número do documento");
        txt_docum_peop.transferFocus();
    }//GEN-LAST:event_txt_docum_peopActionPerformed

    private void cmb_typeDocum_peopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_typeDocum_peopActionPerformed
        cmb_typeDocum_peop.transferFocus();
    }//GEN-LAST:event_cmb_typeDocum_peopActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        componentEnable();
        btn_salvar.setText("Salvar");
        action="save";
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        cleanField();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if (txt_name_peop.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira o nome do cliente");
            txt_name_peop.requestFocus();
        }

        if (txt_docum_peop.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira o número do documento");
            txt_docum_peop.requestFocus();
        }

        if (txt_adress_peop.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira o endereço");
            txt_adress_peop.requestFocus();
        }

        if (txt_cod_cli.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira o código do cliente");
            txt_cod_cli.requestFocus();
        }

        
        if (txt_phone_peop.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira número do telefône");
            txt_phone_peop.requestFocus();
        }        

        if (txt_email_peop.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira o email do cliente");
            txt_email_peop.requestFocus();
        }        
        
        Vclients dts = new  Vclients();
        ConnectClient func = new ConnectClient();

        dts.setName(txt_name_peop.getText());
        dts.setFather(txt_father_peop.getText());
        dts.setMother(txt_mother_peop.getText());
        dts.setAdress(txt_adress_peop.getText());
        dts.setCodClient(txt_cod_cli.getText());
        dts.setDocument(txt_docum_peop.getText());
        dts.setPhone(txt_phone_peop.getText());
        dts.setEmail(txt_email_peop.getText());

        int selectedItem = cmb_typeDocum_peop.getSelectedIndex();
        dts.setTypeDocum((String) cmb_typeDocum_peop.getItemAt(selectedItem));

        if (action.equals("save")){
            if (func.insert(dts)){
                JOptionPane.showMessageDialog(rootPane, "O Cliente foi registrado com sucesso!");
                showSearch("");
                componentDisable();
            }
        }
        else if(action.equals("edit")){
            dts.setIdpeop(Integer.parseInt(txt_id_peop.getText()));

            if (func.edit(dts)){
                JOptionPane.showMessageDialog(rootPane, "O Cliente foi editado com sucesso!");
                showSearch("");
                componentDisable();
            }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void TB_ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_ListaMouseClicked
        btn_salvar.setText("Editar");
        componentEnable();
        btn_apagar.setEnabled(true);
        action="edit";
        int rowActive = TB_Lista.rowAtPoint(evt.getPoint());

        txt_id_peop.setText(TB_Lista.getValueAt(rowActive, 0).toString());
        txt_name_peop.setText(TB_Lista.getValueAt(rowActive, 1).toString());
        txt_father_peop.setText(TB_Lista.getValueAt(rowActive, 2).toString());
        txt_mother_peop.setText(TB_Lista.getValueAt(rowActive, 3).toString());
        cmb_typeDocum_peop.setSelectedItem(TB_Lista.getValueAt(rowActive, 4).toString());
        txt_docum_peop.setText(TB_Lista.getValueAt(rowActive, 5).toString());
        txt_adress_peop.setText(TB_Lista.getValueAt(rowActive, 6).toString());
        txt_phone_peop.setText(TB_Lista.getValueAt(rowActive, 7).toString());
        txt_email_peop.setText(TB_Lista.getValueAt(rowActive, 8).toString());
        txt_cod_cli.setText(TB_Lista.getValueAt(rowActive, 9).toString());
    }//GEN-LAST:event_TB_ListaMouseClicked

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        showSearch(txt_pesquisar.getText());
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        if(!txt_id_peop.getText().equals("")){
            int confirmation = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir esse registro?", "Excluir", 2);
            if (confirmation == 0){
                ConnectClient func = new ConnectClient();
                Vclients dts = new Vclients();
                dts.setIdpeop(Integer.parseInt(txt_id_peop.getText()));
                func.delete(dts);
                showSearch("");
                componentDisable();
            }
        }
    }//GEN-LAST:event_btn_apagarActionPerformed
    
    private void txt_father_peopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_father_peopActionPerformed
    }//GEN-LAST:event_txt_father_peopActionPerformed

    private void txt_mother_peopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mother_peopActionPerformed
    }//GEN-LAST:event_txt_mother_peopActionPerformed

    private void txt_email_peopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_email_peopActionPerformed
    }//GEN-LAST:event_txt_email_peopActionPerformed

    private void txt_phone_peopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phone_peopActionPerformed
    }//GEN-LAST:event_txt_phone_peopActionPerformed

    private void txt_cod_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cod_cliActionPerformed
    }//GEN-LAST:event_txt_cod_cliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_clients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_Lista;
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cmb_typeDocum_peop;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpa_cadQuartos;
    private javax.swing.JPanel jpa_listaQuartos;
    private javax.swing.JScrollPane jsc_adress_peop;
    private javax.swing.JLabel lbl_adress;
    private javax.swing.JLabel lbl_cadQuarto;
    private javax.swing.JLabel lbl_cadQuarto1;
    private javax.swing.JLabel lbl_docum;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_father;
    private javax.swing.JLabel lbl_mother;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_pesquisar;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_registros;
    private javax.swing.JLabel lbl_tipoDoc;
    private javax.swing.JTextArea txt_adress_peop;
    private javax.swing.JTextField txt_cod_cli;
    private javax.swing.JTextField txt_docum_peop;
    private javax.swing.JTextField txt_email_peop;
    private javax.swing.JTextField txt_father_peop;
    private javax.swing.JTextField txt_id_peop;
    private javax.swing.JTextField txt_mother_peop;
    private javax.swing.JTextField txt_name_peop;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_phone_peop;
    // End of variables declaration//GEN-END:variables
}
