/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Data.Vproducts;
import Logic.ConnectFormBedrooms;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabio
 */
public class frm_products extends javax.swing.JFrame {

    /**
     * Creates new form frm_products
     */
    public frm_products() {
        initComponents();
        componentDisable();
        showSearch("null");        
        this.setLocationRelativeTo(null);           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpa_cadQuartos = new javax.swing.JPanel();
        lbl_cadProd = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_und = new javax.swing.JLabel();
        txt_name_prod = new javax.swing.JTextField();
        lbl_descricao = new javax.swing.JLabel();
        jsc_descricao = new javax.swing.JScrollPane();
        txt_descript_prod = new javax.swing.JTextArea();
        lbl_price = new javax.swing.JLabel();
        txt_price_prod = new javax.swing.JTextField();
        cmb_und_prod = new javax.swing.JComboBox<>();
        btn_novo = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        txt_id_prod = new javax.swing.JTextField();
        jpa_listaQuartos = new javax.swing.JPanel();
        lbl_listaProdutos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TB_Lista = new javax.swing.JTable();
        txt_pesquisar = new javax.swing.JTextField();
        lbl_pesquisar = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        lbl_registros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jpa_cadQuartos.setForeground(new java.awt.Color(204, 204, 204));

        lbl_cadProd.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lbl_cadProd.setText("Cadastro de Produtos");

        lbl_name.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_name.setText("Nome");

        lbl_und.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_und.setText("Unidade");

        txt_name_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_name_prodActionPerformed(evt);
            }
        });

        lbl_descricao.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_descricao.setText("Descrição");

        txt_descript_prod.setColumns(20);
        txt_descript_prod.setRows(5);
        jsc_descricao.setViewportView(txt_descript_prod);

        lbl_price.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_price.setText("Valor ");

        txt_price_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_price_prodActionPerformed(evt);
            }
        });

        cmb_und_prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível", "Ocupado", "Manutenção", " " }));
        cmb_und_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_und_prodActionPerformed(evt);
            }
        });

        btn_novo.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/novo.GIF"))); // NOI18N
        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/cancelar.png"))); // NOI18N
        btn_cancelar.setText("Limpar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_salvar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/salvar.png"))); // NOI18N
        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpa_cadQuartosLayout = new javax.swing.GroupLayout(jpa_cadQuartos);
        jpa_cadQuartos.setLayout(jpa_cadQuartosLayout);
        jpa_cadQuartosLayout.setHorizontalGroup(
            jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpa_cadQuartosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpa_cadQuartosLayout.createSequentialGroup()
                        .addComponent(lbl_cadProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpa_cadQuartosLayout.createSequentialGroup()
                        .addComponent(lbl_und)
                        .addGap(23, 23, 23)
                        .addComponent(cmb_und_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_price)
                        .addGap(1, 1, 1)
                        .addComponent(txt_price_prod))
                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                        .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name)
                            .addComponent(lbl_descricao))
                        .addGap(23, 23, 23)
                        .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jsc_descricao)
                            .addComponent(txt_name_prod))))
                .addGap(54, 54, 54))
        );
        jpa_cadQuartosLayout.setVerticalGroup(
            jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadProd)
                    .addComponent(txt_id_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                        .addComponent(txt_name_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsc_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpa_cadQuartosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_descricao)))
                .addGap(32, 32, 32)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_price)
                    .addComponent(cmb_und_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_und)
                    .addComponent(txt_price_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jpa_cadQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpa_listaQuartos.setForeground(new java.awt.Color(204, 204, 204));

        lbl_listaProdutos.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lbl_listaProdutos.setText("Lista de Produtos");

        TB_Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TB_Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_ListaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TB_Lista);

        txt_pesquisar.setName(""); // NOI18N

        lbl_pesquisar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_pesquisar.setText("Pesquisar");

        btn_sair.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/cancelar.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/novo.GIF"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_apagar.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        btn_apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/salvar.png"))); // NOI18N
        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        lbl_registros.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        lbl_registros.setText("Registros");

        javax.swing.GroupLayout jpa_listaQuartosLayout = new javax.swing.GroupLayout(jpa_listaQuartos);
        jpa_listaQuartos.setLayout(jpa_listaQuartosLayout);
        jpa_listaQuartosLayout.setHorizontalGroup(
            jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                        .addGroup(jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_listaProdutos)
                            .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                                .addComponent(lbl_pesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_apagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sair)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpa_listaQuartosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_registros)
                .addGap(31, 31, 31))
        );
        jpa_listaQuartosLayout.setVerticalGroup(
            jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_listaQuartosLayout.createSequentialGroup()
                .addComponent(lbl_listaProdutos)
                .addGap(18, 18, 18)
                .addGroup(jpa_listaQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_sair)
                    .addComponent(btn_apagar)
                    .addComponent(lbl_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_registros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpa_cadQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpa_listaQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpa_listaQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpa_cadQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TB_ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_ListaMouseClicked
        btn_salvar.setText("Editar");
        componentEnable();
        btn_apagar.setEnabled(true);
        action="edit";
        int rowActive = TB_Lista.rowAtPoint(evt.getPoint());

        txt_id_prod.setText(TB_Lista.getValueAt(rowActive, 0).toString());
        txt_name_prod.setText(TB_Lista.getValueAt(rowActive, 1).toString());
        cmb_andar.setSelectedItem(TB_Lista.getValueAt(rowActive, 2).toString());
        txt_descript_prod.setText(TB_Lista.getValueAt(rowActive, 3).toString());
        txt_caracteristica.setText(TB_Lista.getValueAt(rowActive, 4).toString());
        txt_price_prod.setText(TB_Lista.getValueAt(rowActive, 5).toString());
        cmb_und_prod.setSelectedItem(TB_Lista.getValueAt(rowActive, 6).toString());
        cmb_tipoQuarto.setSelectedItem(TB_Lista.getValueAt(rowActive, 7).toString());

    }//GEN-LAST:event_TB_ListaMouseClicked

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        showSearch(txt_pesquisar.getText());
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        if(!txt_id_prod.getText().equals("")){
            int confirmation = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir esse quarto?", "Excluir", 2);
            if (confirmation == 0){
                ConnectFormBedrooms func = new ConnectFormBedrooms();
                Vbedrooms dts = new Vbedrooms();
                dts.setIdBedrooms(Integer.parseInt(txt_id_prod.getText()));
                func.delete(dts);
                showSearch("");
                componentDisable();
            }
        }
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if (txt_name_prod.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira o número do quarto");
            txt_name_prod.requestFocus();
        }

        if (txt_descript_prod.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira a descrição para o quarto");
            txt_descript_prod.requestFocus();
        }

        if (txt_caracteristica.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira uma caracteristica para o quarto");
            txt_caracteristica.requestFocus();
        }

        if (txt_price_prod.getText().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "Insira o valor da diária");
            txt_price_prod.requestFocus();
        }

        Vbedrooms dts = new  Vbedrooms();
        ConnectFormBedrooms func = new ConnectFormBedrooms();

        dts.setNumber(txt_name_prod.getText());
        dts.setValueDaily(Double.parseDouble(txt_price_prod.getText()));
        dts.setDescription(txt_descript_prod.getText());
        dts.setCharacteristics(txt_caracteristica.getText());

        int selectedItem = cmb_andar.getSelectedIndex();
        dts.setFloor((String) cmb_andar.getItemAt(selectedItem));

        selectedItem = cmb_und_prod.getSelectedIndex();
        dts.setState((String) cmb_und_prod.getItemAt(selectedItem));

        selectedItem = cmb_tipoQuarto.getSelectedIndex();
        dts.setTypeBedroom((String) cmb_tipoQuarto.getItemAt(selectedItem));

        if (action.equals("save")){
            if (func.insert(dts)){
                JOptionPane.showMessageDialog(rootPane, "O Quarto foi registrado com sucesso!");
                showSearch("");
                componentDisable();
            }
        }
        else if(action.equals("edit")){
            dts.setIdBedrooms(Integer.parseInt(txt_id_prod.getText()));

            if (func.edit(dts)){
                JOptionPane.showMessageDialog(rootPane, "O Quarto foi editado com sucesso!");
                showSearch("");
                componentDisable();
            }
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        cleanField();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        componentEnable();
        btn_salvar.setText("Salvar");
        action="save";
        btn_novo.enable(false);
    }//GEN-LAST:event_btn_novoActionPerformed

    private void cmb_und_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_und_prodActionPerformed
        cmb_und_prod.transferFocus();
    }//GEN-LAST:event_cmb_und_prodActionPerformed

    private void txt_price_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_price_prodActionPerformed
        txt_price_prod.transferFocus();
    }//GEN-LAST:event_txt_price_prodActionPerformed

    private void txt_name_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_name_prodActionPerformed
        txt_name_prod.transferFocus();
    }//GEN-LAST:event_txt_name_prodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_Lista;
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cmb_und_prod;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpa_cadQuartos;
    private javax.swing.JPanel jpa_listaQuartos;
    private javax.swing.JScrollPane jsc_descricao;
    private javax.swing.JLabel lbl_cadProd;
    private javax.swing.JLabel lbl_descricao;
    private javax.swing.JLabel lbl_listaProdutos;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_pesquisar;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_registros;
    private javax.swing.JLabel lbl_und;
    private javax.swing.JTextArea txt_descript_prod;
    private javax.swing.JTextField txt_id_prod;
    private javax.swing.JTextField txt_name_prod;
    private javax.swing.JTextField txt_pesquisar;
    private javax.swing.JTextField txt_price_prod;
    // End of variables declaration//GEN-END:variables
}
